import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/homepage">HOMEPAGE</Link>
        </li>
        <li>
          <Link to="/signuppage">Signuppage</Link>
        </li>
        <li>
          <Link to="/surfacepro8six">SurfacePro8Six</Link>
        </li>
        <li>
          <Link to="/bookspage">BOOKSPAGE</Link>
        </li>
        <li>
          <Link to="/exporingbookspage">EXPORINGBOOKSPAGE</Link>
        </li>
        <li>
          <Link to="/booksdetailspage">BOOKSDETAILSPAGE</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
